name = "spotify-stats"
main = "src/index.ts"
compatibility_date = "2026-01-18"

routes = [
	{ pattern = "top-lists.lukaspanni.de", custom_domain = true}
]
preview_urls = true

[assets]
directory = "./dist/public"
